name: The Bright Boutique
favicon: null
layout_spectrum: 0.49143
typography_spectrum: 0.67445
title: The Bright Boutique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221e1f'
    - '#ed2590'
    - '#fffdff'
    - '#d97baf'
    - '#f3c2e3'
  brandStrength: 0.375
  lightness: 0.695671352557838
  saturation: 0.9019199053291231
  rhythmicContrast: 0.7459451402537525
purpose: []
