name: The Bright Boutique
favicon: null
layout_spectrum: 0.24169365875422955
typography_spectrum: 0.6822741311043501
title: The Bright Boutique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3267088537104428
  lightness: 0.695671352557838
  saturation: 0.9019199053291231
  rhythmicContrast: 0.7459451402537525
purpose: []
